# Generated by Django 5.0.1 on 2024-01-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='menu',
            field=models.CharField(blank=True, choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER')], max_length=50, null=True),
        ),
    ]
