# Generated by Django 5.0.1 on 2024-01-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='core/menu_1.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='menu',
            field=models.CharField(blank=True, choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('all_day', 'ALL_DAY')], max_length=50, null=True),
        ),
    ]
