# Generated by Django 5.0.1 on 2024-01-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
