# Generated by Django 5.0.1 on 2024-01-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categoryproduct_products_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_product',
        ),
        migrations.AddField(
            model_name='products',
            name='category_product',
            field=models.ManyToManyField(blank=True, related_name='category', to='products.categoryproduct'),
        ),
    ]
