# Generated by Django 5.0.1 on 2024-01-13 16:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_category_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='menu_1.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='menu',
            field=models.CharField(blank=True, choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('happy_hour', 'HAPPY_HOUR'), ('all_day', 'ALL_DAY')], max_length=50, null=True),
        ),
    ]
